// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzhKUao8_K675e5wpJzPG1elDkZOJ5mAI',
    appId: '1:109321411513:web:5700f140b311e464aeb468',
    messagingSenderId: '109321411513',
    projectId: 'budgeting-app-81c05',
    authDomain: 'budgeting-app-81c05.firebaseapp.com',
    storageBucket: 'budgeting-app-81c05.appspot.com',
    measurementId: 'G-T4GRWTCQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4If1aKWXUwdlwicE9ikjykEie0ghtNk',
    appId: '1:109321411513:android:e2eb2b272166d9d3aeb468',
    messagingSenderId: '109321411513',
    projectId: 'budgeting-app-81c05',
    storageBucket: 'budgeting-app-81c05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Ei4ZLvAH_wYvh34P4IpXmLSbCyrFvqc',
    appId: '1:109321411513:ios:0140fd2975aa2c95aeb468',
    messagingSenderId: '109321411513',
    projectId: 'budgeting-app-81c05',
    storageBucket: 'budgeting-app-81c05.appspot.com',
    iosBundleId: 'com.amar.budgetingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Ei4ZLvAH_wYvh34P4IpXmLSbCyrFvqc',
    appId: '1:109321411513:ios:0140fd2975aa2c95aeb468',
    messagingSenderId: '109321411513',
    projectId: 'budgeting-app-81c05',
    storageBucket: 'budgeting-app-81c05.appspot.com',
    iosBundleId: 'com.amar.budgetingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzhKUao8_K675e5wpJzPG1elDkZOJ5mAI',
    appId: '1:109321411513:web:cf99b2258cec9a3aaeb468',
    messagingSenderId: '109321411513',
    projectId: 'budgeting-app-81c05',
    authDomain: 'budgeting-app-81c05.firebaseapp.com',
    storageBucket: 'budgeting-app-81c05.appspot.com',
    measurementId: 'G-QZ33Z64QM5',
  );
}
